---
title: "APM466 A1"
author: "Jiayuan Pan, student ID:1004811910"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading data and generate date measure
```{r Setup, message=FALSE}
library(readxl)
library(tidyverse)
library(SciViews)
library(nleqslv)
library(reshape)
library(NLRoot)
library(janitor)
library(WriteXLS)
library(dplyr)

#load in data and save in R
APM466_A1_data <- read_excel("~/Desktop/APM466_A1_data.xlsx")
WriteXLS(APM466_A1_data, ExcelFileName = "APM466_A1_data.xlsx")
data <- APM466_A1_data 
```

```{r}
#convert the date to class date formatting
data[,3] = as.Date(data$`Issue date`,format='%Y/%m/%d')
data[,5] = as.Date(data$`Maturity date`,format='%Y/%m/%d')


#generate new variables to identify date of observation
data <- data %>% 
  mutate(date_1 = as.Date('2022/1/10',format='%Y/%m/%d')) %>%
  mutate(date_2 = as.Date('2022/1/11',format='%Y/%m/%d')) %>%
  mutate(date_3 = as.Date('2022/1/12',format='%Y/%m/%d')) %>%
  mutate(date_4 = as.Date('2022/1/13',format='%Y/%m/%d')) %>%
  mutate(date_5 = as.Date('2022/1/13',format='%Y/%m/%d')) %>%
  mutate(date_6 = as.Date('2022/1/17',format='%Y/%m/%d')) %>%
  mutate(date_7 = as.Date('2022/1/18',format='%Y/%m/%d')) %>%
  mutate(date_8 = as.Date('2022/1/19',format='%Y/%m/%d')) %>%
  mutate(date_9 = as.Date('2022/1/20',format='%Y/%m/%d')) %>%
  mutate(date_10 = as.Date('2022/1/21',format='%Y/%m/%d'))

#generate time to maturity according to observation date
data$date_1_TTM <- as.numeric((data$`Maturity date`- data$date_1), units="days")/365
data$date_2_TTM <- as.numeric((data$`Maturity date`- data$date_2), units="days")/365
data$date_3_TTM <- as.numeric((data$`Maturity date`- data$date_3), units="days")/365
data$date_4_TTM <- as.numeric((data$`Maturity date`- data$date_4), units="days")/365
data$date_5_TTM <- as.numeric((data$`Maturity date`- data$date_5), units="days")/365
data$date_6_TTM <- as.numeric((data$`Maturity date`- data$date_6), units="days")/365
data$date_7_TTM <- as.numeric((data$`Maturity date`- data$date_7), units="days")/365
data$date_8_TTM <- as.numeric((data$`Maturity date`- data$date_8), units="days")/365
data$date_9_TTM <- as.numeric((data$`Maturity date`- data$date_9), units="days")/365
data$date_10_TTM <- as.numeric((data$`Maturity date`- data$date_10), units="days")/365

#notional: the payment occur at maturity
N=100
#change the coupon rate to per 100 dollars instead of percentage
data$`Coupon rate` = (data$`Coupon rate`)*100
```

## Question 4:

```{r}
#define function to calculate ytm from non-linear equation by Newton's method
NW <- function (f, f1, x0 = 0, num = 100, eps = 1e-05, eps1 = 1e-05) 
{   a = x0
    b = a - f(a)/f1(a)
    i = 0
    while ((abs(b - a) > eps) & (i < num)) {
        a = b
        b = a - f(a)/f1(a)
        i = i + 1}
    if (abs(f(b)) < eps1) {
        return(a)}
    else print("finding root is fail")
}
```


```{r}
#calculate the yield to maturity for each bond on each day. (YTM curve)
rep(NA, 10) -> ytm_bond_1 -> ytm_bond_2 -> ytm_bond_3 -> ytm_bond_4 -> ytm_bond_5 -> ytm_bond_6 -> ytm_bond_7 -> ytm_bond_8 -> ytm_bond_9 -> ytm_bond_10 -> ytm_bond_11

#calculate the yield curve/spot curve for each day. (Yield/Spot curve)
#Bootstrapping Method for finding the spot rate and plot the yield curve
#the Bootstrapping method allows us to use coupon-payment bond to recover yield curve, 
rep(NA, 10) -> spot_1 -> spot_2 -> spot_3 -> spot_4 -> spot_5 -> spot_6 -> spot_7 -> spot_8 -> spot_9 -> spot_10 -> spot_11


for (i in 1:10){#iteration over 10 days of observation
  #find yield for each bond 
  
  b=1;c=data[b,4]/2
  #ytm
  ytm_bond_1[i]= as.numeric(-ln(((data[b,5+i]))/(N+c))
                            /(data[b,25+i]))
  #spot rate
  spot_1[i] = as.numeric(-ln((data[b,5+i])/(N+c))/(data[b,25+i]))
  
  b=2;c=data[b,4]/2
  for (j in 1:2){assign(paste("t2", j, sep="_"), data[b,25+i]-(2-j)*0.5)} 
  #ytm
  f <- NW(function(x) (-1)*(data[b,5+i])+c*exp(-t2_1*x)+(100+c)*exp(-t2_2*x),
          function(x) c*exp(-t2_1*x)*(-t2_1)+(100+c)*exp(-t2_2*x)*(-t2_2), x0 = 0)
  ytm_bond_2[i]= as.numeric(f)
  #spot rate
  spot_2[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t2_1*spot_1[i]))/(100+c)))/t2_2)

  b=3;c=data[b,4]/2
  for (j in 1:3){assign(paste("t3", j, sep="_"), data[b,25+i]-(3-j)*0.5)}  
  #ytm
  f <- NW(function(x) (-1)*(data[b,5+i])+c*exp(-t3_1*x)+c*exp(-t3_2*x)+(100+c)*exp(-t3_3*x),
          function(x) (c*exp(-t3_1*x)*(-t3_1)+c*exp(-t3_2*x)*(-t3_2)
                      +(100+c)*exp(-t3_3*x)*(-t3_3)), x0 = 0)
  ytm_bond_3[i]= as.numeric(f)
  #spot rate
  spot_3[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t3_1*spot_1[i])-c*exp(-t3_2*spot_2[i]))
                       /(100+c)))/t3_3)
 
  b=4;c=data[b,4]/2
  for (j in 1:4){assign(paste("t4", j, sep="_"), data[b,25+i]-(4-j)*0.5)} 
  #ytm
  f <- NW(function(x) ((-1)*(data[b,5+i])+c*exp(-t4_1*x)+c*exp(-t4_2*x)
                       +c*exp(-t4_3*x)+(100+c)*exp(-t4_4*x)),
          function(x) (c*exp(-t4_1*x)*(-t4_1)+c*exp(-t4_2*x)*(-t4_2)+ 
                       c*exp(-t4_3*x)*(-t4_3)+(100+c)*exp(-t4_4*x)*(-t4_4)), x0 = 0)
  ytm_bond_4[i] = as.numeric(f)
  #spot rate
  spot_4[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t4_1*spot_1[i])
                     -c*exp(-t4_2*spot_2[i])
                     -c*exp(-t4_3*spot_3[i]))/(100+c)))/t4_4)
  
  b=5;c=data[b,4]/2
  for (j in 1:5){assign(paste("t5", j, sep="_"), data[b,25+i]-(5-j)*0.5)}  
  #ytm
  f <- NW(function(x) ((-1)*(data[b,5+i])+c*exp(-t5_1*x)+c*exp(-t5_2*x)
                       +c*exp(-t5_3*x)+c*exp(-t5_4*x)+(100+c)*exp(-t5_5*x)),
          function(x) (c*exp(-t5_1*x)*(-t5_1)+c*exp(-t5_2*x)*(-t5_2)+ 
                       c*exp(-t5_3*x)*(-t5_3)+c*exp(-t5_4*x)*(-t5_4)+
                         (100+c)*exp(-t5_5*x)*(-t5_5)), x0 = 0)
  ytm_bond_5[i]= as.numeric(f)
  #spot rate
  spot_5[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t5_1*spot_1[i])
                        -c*exp(-t5_2*spot_2[i])
                        -c*exp(-t5_3*spot_3[i])
                        -c*exp(-t5_3*spot_4[i]))/
                         (100+c)))/t5_5)
  
  b=6; c=data[b,4]/2
  for (j in 1:6){assign(paste("t6", j, sep="_"), data[b,25+i]-(6-j)*0.5)} 
  #ytm
  f <- NW(function(x) (-1)*((data[b,5+i]))+c*exp(-t6_1*x)+c*exp(-t6_2*x)
                       +c*exp(-t6_3*x)+c*exp(-t6_4*x)+c*exp(-t6_5*x)+(100+c)*exp(-t6_6*x),
          function(x) (c*exp(-t6_1*x)*(-t6_1)+c*exp(-t6_2*x)*(-t6_2)+ 
                       c*exp(-t6_3*x)*(-t6_3)+c*exp(-t6_4*x)*(-t6_4)+
                       c*exp(-t6_5*x)*(-t6_5)+(100+c)*exp(-t6_6*x)*(-t6_6)), x0 = 0)
  ytm_bond_6[i] = as.numeric(f)
  #spot rate
  spot_6[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t6_1*spot_1[i])
                        -c*exp(-t6_2*spot_2[i])
                        -c*exp(-t6_3*spot_3[i])
                        -c*exp(-t6_4*spot_4[i])
                        -c*exp(-t6_5*spot_5[i]))/
                         (100+c)))/t6_5)
  
  b=7; c=data[b,4]/2
  for (j in 1:7){assign(paste("t7", j, sep="_"), data[b,25+i]-(7-j)*0.5)}
  #ytm
  f <- NW(function(x) ((-1)*((data[b,5+i]))+c*exp(-t7_1*x)+c*exp(-t7_2*x)
                       +c*exp(-t7_3*x)+c*exp(-t7_4*x)+c*exp(-t7_5*x)
                       +c*exp(-t7_6*x)+(100+c)*exp(-t7_7*x)),
          function(x) (c*exp(-t7_1*x)*(-t7_1)+c*exp(-t7_2*x)*(-t7_2)+ 
                       c*exp(-t7_3*x)*(-t7_3)+c*exp(-t7_4*x)*(-t7_4)+
                       c*exp(-t7_5*x)*(-t7_5)+c*exp(-t7_6*x)*(-t7_6)+
                       (100+c)*exp(-t7_7*x)*(-t7_7)), x0 = 0)
  ytm_bond_7[i]= as.numeric(f)
  #spot rate
  spot_7[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t7_1*spot_1[i])
                        -c*exp(-t7_2*spot_2[i])
                        -c*exp(-t7_3*spot_3[i])
                        -c*exp(-t7_4*spot_4[i])
                        -c*exp(-t7_5*spot_5[i])
                        -c*exp(-t7_6*spot_6[i]))/
                         (100+c)))/t7_7)
  
  b=8;c=data[b,4]/2
  for (j in 1:8){assign(paste("t8", j, sep="_"), data[b,25+i]-(8-j)*0.5)}
  #ytm
  f <- NW(function(x) ((-1)*(data[b,5+i])+c*exp(-t8_1*x)+c*exp(-t8_2*x)
                       +c*exp(-t8_3*x)+c*exp(-t8_4*x)+c*exp(-t8_5*x)
                       +c*exp(-t8_6*x)+c*exp(-t8_7*x)+(100+c)*exp(-t8_8*x)),
          function(x) (c*exp(-t8_1*x)*(-t8_1)+c*exp(-t8_2*x)*(-t8_2)+ 
                       c*exp(-t8_3*x)*(-t8_3)+c*exp(-t8_4*x)*(-t8_4)+
                       c*exp(-t8_5*x)*(-t8_5)+c*exp(-t8_6*x)*(-t8_6)+
                       c*exp(-t8_7*x)*(-t8_7)+(100+c)*exp(-t8_8*x)*(-t8_8)), x0 = 0)
  ytm_bond_8[i]= as.numeric(f)
  #spot rate
  spot_8[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t8_1*spot_1[i])
                        -c*exp(-t8_2*spot_2[i])
                        -c*exp(-t8_3*spot_3[i])
                        -c*exp(-t8_4*spot_4[i])
                        -c*exp(-t8_5*spot_5[i])
                        -c*exp(-t8_6*spot_6[i])
                        -c*exp(-t8_7*spot_7[i]))/
                         (100+c)))/t8_8)
  
  b=9;c=data[b,4]/2
  for (j in 1:9){assign(paste("t9", j, sep="_"), data[b,25+i]-(9-j)*0.5)}
  #ytm
  f <- NW(function(x) ((-1)*(data[b,5+i])+c*exp(-t9_1*x)+c*exp(-t9_2*x)
                       +c*exp(-t9_3*x)+c*exp(-t9_4*x)+c*exp(-t9_5*x)
                       +c*exp(-t9_6*x)+c*exp(-t9_7*x)+c*exp(-t9_8*x)+
                       (100+c)*exp(-t9_9*x)),
          function(x) (c*exp(-t9_1*x)*(-t9_1)+c*exp(-t9_2*x)*(-t9_2)+ 
                       c*exp(-t9_3*x)*(-t9_3)+c*exp(-t9_4*x)*(-t9_4)+
                       c*exp(-t9_5*x)*(-t9_5)+c*exp(-t9_6*x)*(-t9_6)+
                       c*exp(-t9_7*x)*(-t9_7)+c*exp(-t9_8*x)*(-t9_8)+
                       (100+c)*exp(-t9_9*x)*(-t9_9)), x0 = 0)
  ytm_bond_9[i]= as.numeric(f)
  #spot rate
  spot_9[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t9_1*spot_1[i])
                        -c*exp(-t9_2*spot_2[i])
                        -c*exp(-t9_3*spot_3[i])
                        -c*exp(-t9_4*spot_4[i])
                        -c*exp(-t9_5*spot_5[i])
                        -c*exp(-t9_6*spot_6[i])
                        -c*exp(-t9_7*spot_7[i])
                        -c*exp(-t9_8*spot_8[i]))/
                         (100+c)))/t9_9)
  
  b=10;c=data[b,4]/2
  for (j in 1:10){assign(paste("t10", j, sep="_"), data[b,25+i]-(10-j)*0.5)}
  #ytm
  f <- NW(function(x) ((-1)*(data[b,5+i])+c*exp(-t10_1*x)+c*exp(-t10_2*x)
                       +c*exp(-t10_3*x)+c*exp(-t10_4*x)+c*exp(-t10_5*x)
                       +c*exp(-t10_6*x)+c*exp(-t10_7*x)+c*exp(-t10_8*x)
                       +c*exp(-t10_9*x)+(100+c)*exp(-t10_10*x)),
          function(x) (c*exp(-t10_1*x)*(-t10_1)+c*exp(-t10_2*x)*(-t10_2)+ 
                       c*exp(-t10_3*x)*(-t10_3)+c*exp(-t10_4*x)*(-t10_4)+
                       c*exp(-t10_5*x)*(-t10_5)+c*exp(-t10_6*x)*(-t10_6)+
                       c*exp(-t10_7*x)*(-t10_7)+c*exp(-t10_8*x)*(-t10_8)+
                       c*exp(-t10_9*x)*(-t10_9)+(100+c)*exp(-t10_10*x)*(-t10_10)), x0 = 0)
  ytm_bond_10[i]= as.numeric(f)
  #spot rate
  spot_10[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t10_1*spot_1[i])
                        -c*exp(-t10_2*spot_2[i])
                        -c*exp(-t10_3*spot_3[i])
                        -c*exp(-t10_4*spot_4[i])
                        -c*exp(-t10_5*spot_5[i])
                        -c*exp(-t10_6*spot_6[i])
                        -c*exp(-t10_7*spot_7[i])
                        -c*exp(-t10_8*spot_8[i])
                        -c*exp(-t10_9*spot_9[i]))/
                         (100+c)))/t10_10)
  
  b=11;c=data[b,4]/2
  for (j in 1:11){assign(paste("t11", j, sep="_"), data[b,25+i]-(11-j)*0.5)}

  #ytm
  f <- NW(function(x) ((-1)*(data[b,5+i])+c*exp(-t11_1*x)+c*exp(-t11_2*x)
                       +c*exp(-t11_3*x)+c*exp(-t11_4*x)+c*exp(-t11_5*x)
                       +c*exp(-t11_6*x)+c*exp(-t11_7*x)+c*exp(-t11_8*x)
                       +c*exp(-t11_9*x)+c*exp(-t11_10*x)+(100+c)*exp(-t11_11*x)),
          function(x) (c*exp(-t11_1*x)*(-t11_1)+c*exp(-t11_2*x)*(-t11_2)+ 
                       c*exp(-t11_3*x)*(-t11_3)+c*exp(-t11_4*x)*(-t11_4)+
                       c*exp(-t11_5*x)*(-t11_5)+c*exp(-t11_6*x)*(-t11_6)+
                       c*exp(-t11_7*x)*(-t11_7)+c*exp(-t11_8*x)*(-t11_8)+
                       c*exp(-t11_9*x)*(-t11_9)+c*exp(-t11_10*x)*(-t11_10)+
                       (100+c)*exp(-t11_11*x)*(-t11_11)), x0 = 0)
  ytm_bond_11[i]= as.numeric(f)
  #spot rate
  spot_11[i] = as.numeric((-ln(((data[b,5+i])-c*exp(-t11_1*spot_1[i])
                        -c*exp(-t11_2*spot_2[i])
                        -c*exp(-t11_3*spot_3[i])
                        -c*exp(-t11_4*spot_4[i])
                        -c*exp(-t11_5*spot_5[i])
                        -c*exp(-t11_6*spot_6[i])
                        -c*exp(-t11_7*spot_7[i])
                        -c*exp(-t11_8*spot_8[i])
                        -c*exp(-t11_9*spot_9[i])
                        -c*exp(-t11_10*spot_10[i]))/
                         (100+c)))/t11_11)
}
```

### Part a: Yield to Maturity Curve
```{r}
#plot ytm curve
ytm_table <-cbind(ytm_bond_1, ytm_bond_2, ytm_bond_3, ytm_bond_4,
                   ytm_bond_5, ytm_bond_6, ytm_bond_7, ytm_bond_8, 
                   ytm_bond_9, ytm_bond_10, ytm_bond_11)
for (i in 1:10){
  assign(paste("ytm_day", i, sep="_"), ytm_table[i,])
}

ytm_day_table <-data.frame(bond_order =c(1:11), ytm_day_1, ytm_day_2, ytm_day_3, ytm_day_4, ytm_day_5, ytm_day_6, ytm_day_7, ytm_day_8, ytm_day_8, ytm_day_10)


plot(x=data$date_1_TTM, y= ytm_day_1, type = "l", ylim = c(0.005,0.025), col = c(1),
     main = "Yield-to-Maturity Curve for each day (Jan.10 to Jan.21)",
     xlab = "Duration", ylab="YTM")
lines(x=data$date_2_TTM, y= ytm_day_2, col = c(2))
lines(x=data$date_3_TTM, y= ytm_day_3, col = c(3))
lines(x=data$date_4_TTM, y= ytm_day_4, col = c(4))
lines(x=data$date_5_TTM, y= ytm_day_5, col = c(5))
lines(x=data$date_6_TTM, y= ytm_day_6, col = c(6))
lines(x=data$date_7_TTM, y= ytm_day_7, col = c(7))
lines(x=data$date_8_TTM, y= ytm_day_8, col = c(8))
lines(x=data$date_9_TTM, y= ytm_day_9, col = c(9))
lines(x=data$date_10_TTM, y= ytm_day_10, col = c(10))
legend("bottomright", legend =c("Jan-10-2022", "Jan-11-2022", "Jan-12-2022", "Jan-13-2022", "Jan-14-2022", "Jan-17-2022", "Jan-18-2022", "Jan-19-2022", "Jan-20-2022","Jan-21-2022"), col=c(1:10), lty = 1:1, cex =0.5)

```

### Part b: Yield/Spot Curve
```{r}
#plot spot curve
spot_table <-data.frame(yield_1, yield_2, yield_3, yield_4, yield_5, 
            yield_6, yield_7, yield_8, yield_9, yield_10, yield_11)

for (i in 1:10){
  assign(paste("spot_day", i, sep="_"), spot_table[i,])
}

spot_day_table <-data.frame(bond_order =c(1:11), spot_day_1, spot_day_2, spot_day_3, spot_day_4, spot_day_5, spot_day_6, spot_day_7, spot_day_8, spot_day_9, spot_day_10)


plot(x=data$date_1_TTM, y= spot_day_1, type = "l", ylim = c(0.005,0.025), col = c(1), 
     main = "Spot Curve for each day (Jan.10 to Jan.21)",
     xlab = "Time to Maturity (units:years)", ylab="Spot Rate")
lines(x=data$date_2_TTM, y= spot_day_2, col = c(2))
lines(x=data$date_3_TTM, y= spot_day_3, col = c(3))
lines(x=data$date_4_TTM, y= spot_day_4, col = c(4))
lines(x=data$date_5_TTM, y= spot_day_5, col = c(5))
lines(x=data$date_6_TTM, y= spot_day_6, col = c(6))
lines(x=data$date_7_TTM, y= spot_day_7, col = c(7))
lines(x=data$date_8_TTM, y= spot_day_8, col = c(8))
lines(x=data$date_9_TTM, y= spot_day_9, col = c(9))
lines(x=data$date_10_TTM, y= spot_day_10, col = c(10))
legend("bottomright", legend =c("Jan-10-2022", "Jan-11-2022", "Jan-12-2022", "Jan-13-2022", "Jan-14-2022", "Jan-17-2022", "Jan-18-2022", "Jan-19-2022", "Jan-20-2022","Jan-21-2022"), col=c(1:10), lty = 1:1, cex =0.5)


```


### Part c: Forward Rate Curve
```{r}

```


## Question 5:
### Part a: Covariance Matrix
```{r}
#find the covariance matrix for the log-returns of yield

```

```{r}
#find the covariance matrix for the log-returns of forward rate 
```




### Part b: Eigenvalue and Eigenvector of Covariance Matrix
```{r}

```

